- name: Configure and Build iPXE
  gather_facts: false
  hosts: all
  vars:
    ipxe_bin_path: /home/ipxe/src/bin
    ipxe_files:
      - ipxe.lkrn
      - ipxe.pxe
      - undionly.kpxe
    pkgs:
      - git
      - make
      - build-essential
      - genisoimage
      - mkisofs
      - liblzma-dev
  tasks:
# Normally I would _always_ use a module vs a command
# Since we are doing this inside a container and didn't
# want to install additional dependencies I am using command
# instead.
    - name: Dependency to build iPXE
      command: apt-get -y install {{ item }}
      with_items: pkgs
    - name: Clone iPXE
      git:
        repo: git://git.ipxe.org/ipxe.git
        dest: /home/ipxe
    
    - name: Configure (uncomment) Console PC BIOS Usage All
      lineinfile:
        dest: /home/ipxe/src/config/console.h
        regexp: "//#define.*CONSOLE_PCBIOS.*"
        line: "#define\tCONSOLE_PCBIOS CONSOLE_USAGE_ALL"
        state: present
    
    - name: Configure (uncomment) Console Syslog Usage All
      lineinfile:
        dest: /home/ipxe/src/config/console.h
        regexp: "//#define.*CONSOLE_SYSLOG.*"
        line: "#define\tCONSOLE_SYSLOG\tCONSOLE_USAGE_ALL"
        state: present
    
    - name: Configure (uncomment) SYSLINUX COMBOOT image support
      lineinfile:
        dest: /home/ipxe/src/config/general.h
        regexp: "//#define.*IMAGE_COMBOOT.*"
        line: "#define\tIMAGE_COMBOOT"
        state: present
    
    - name: Remove define for Console PC BIOS
      lineinfile:
        dest: /home/ipxe/src/config/defaults/pcbios.h
        regexp: "#define.*CONSOLE_PCBIOS.*"
        state: absent
    
    - name: Configure (uncomment) IPSTAT Command
      lineinfile:
        dest: /home/ipxe/src/config/general.h
        regexp: "//#define.*IPSTAT_CMD.*"
        line: "#define\tIPSTAT_CMD"
        state: absent
    
    - name: Configure (uncomment) PROFSTAT Command
      lineinfile:
        dest: /home/ipxe/src/config/general.h
        regexp: "//#define.*PROFSTAT_CMD.*"
        line: "#define\tPROFSTAT_CMD"
        state: absent

    - name: Create tftpboot directory
      file:
        path: /tftpboot/
        state: directory
        owner: nobody
        group: nogroup

    - name: Build iPXE without debug options 
      command: 'make -j2 chdir=/home/ipxe/src'
          
    - name: Copy iPXE files to tftpboot
      copy:
        src: "{{ ipxe_bin_path }}/{{ item }}"
        dest: /tftpboot/
        owner: nobody
        group: nogroup
        mode: 0700 
      with_items: ipxe_files

    - name: Make Clean 
      command: 'make veryclean chdir=/home/ipxe/src'

    - name: Build iPXE with debug options
      command: 'make -j2 DEBUG=httpcore:3,monojob:3,pxe_image:3,intel:0 chdir=/home/ipxe/src'
    
    - name: Copy iPXE files to tftpboot
      copy:
        src: "{{ ipxe_bin_path }}/{{ item }}"
        dest: "/tftpboot/{{ item | replace('.', '-debug.' ) }}"
        owner: nobody
        group: nogroup
        mode: 0700
      with_items: ipxe_files

    - name: Remove all iPXE source files
      file:
        path: /home/ipxe/
        state: absent

    - name: Remove all unneeded packages
      command: apt-get -y purge {{ item }}
      with_items: pkgs

    - name: Autoremove all packages
      command: apt-get -y autoremove
